https://github.com/KacperBudnik/AiSD/tree/main/List%205

# Zadanie 1

In [1]:
import numpy as np
from scipy import linalg
import timeit
import random

In [2]:
a = np.array([[3,2,0],[1,-1,0],[0,5,1]])

In [3]:
b = np.array([2, 4, -1])

In [4]:
x = linalg.solve(a,b)

In [5]:
x

array([ 2., -2.,  9.])

In [13]:
np.dot(a,x) == b

array([ True,  True,  True])

In [92]:
def solve_n_res(n,a=-50,b=50):
    x=np.random.randint(a,b+1,n)
    A=np.random.randint(a,b+1,(n,n))
    b=[sum(x[i]*a[i] for i in range(n)) for a in A]
    return (x,A,b)

In [87]:
x=solve_n_res(100)

In [88]:
x

(array([-22,  48,  22, -34,   4, -40, -26,  33,  13,   3,  41, -13, -50,
          8,  47,  44, -42, -19,  -4,  26,  21, -32,  15, -30,   4, -30,
        -10,   4, -32,  31, -38,  40,  -3,  12, -35, -36, -41,  -8,  15,
        -36,  36,  47,  15,  37, -34,   7, -32,   9,  -1,  -8, -38,  49,
         11,  22,  37,  39, -14,  35,  -6, -48, -44,  23,   9,  40,  17,
        -11,  26, -16, -20,   1,   2, -16, -27, -21, -48,  50,  24,  31,
         46,  19, -41,  47, -11,  37, -22,  27,  35,  13,  34,  -4, -40,
        -47,  36, -34,  44, -43, -44, -43, -21,  21]),
 array([[-48,   8,  18, ...,  39,   9,   0],
        [-20,  19,  42, ..., -50,  -3, -38],
        [  6, -13,  21, ...,  49,   1, -16],
        ...,
        [  8, -28, -16, ..., -42, -24,  34],
        [ -2,  28, -43, ...,  32,  33,   5],
        [ 19, -12,  -3, ...,  17, -18,  27]]),
 [-4967,
  2952,
  2804,
  2352,
  6635,
  7737,
  2073,
  -811,
  6649,
  16445,
  13067,
  6454,
  -16701,
  3917,
  23010,
  -3243,
  -622,
  -495

In [89]:
all(np.dot(x[1],x[0])==x[2])

True

In [133]:
def solve_n(n,a=-50,b=50):
    x=np.random.randint(a,b+1,n)
    A=np.random.randint(a,b+1,(n,n))
    b=[sum(x[i]*a[i] for i in range(n)) for a in A]

    
    return timeit.timeit("linalg.solve(A,b)","from scipy import linalg",number=1,globals=locals())

In [134]:
solve_n(10)

0.00017989999969358905

In [143]:
solve_n(10000)

1

In [142]:
def solve_n(n,a=-50,b=50):
    x=np.random.randint(a,b+1,n)
    A=np.random.randint(a,b+1,(n,n))
    b=[sum(x[i]*a[i] for i in range(n)) for a in A]

    
    return 1

# n=1e4

In [156]:
x=np.random.randint(-100,100,50000)

In [154]:
A=np.random.randint(-100,100,(50000,50000))

In [155]:
A

array([[  7, -55,  18, ...,  61, -20,   9],
       [-86,  71, -32, ...,  67, -91,  94],
       [-67,  42, -73, ..., -22, -27, -67],
       ...,
       [-83,  54,  10, ...,  87, -94,  18],
       [-49, -11, -87, ..., -77,   9,  37],
       [ 63, -68, -61, ...,  -4, -76,  84]])

# n=5e4

In [9]:
times=np.zeros(15)

# n=2

In [39]:
n=2

In [40]:
b=np.random.randint(-2**10,2**10,n)

In [41]:
A=[[0]]
while linalg.det(A)==0:
    A=np.random.randint(-2**10,2**10,(n,n))

In [42]:
b=[sum(x[i]*a[i] for i in range(n)) for a in A]

In [45]:
times[0]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=1)

0.0001732000000060907

LinAlgError: Matrix is singular.

In [23]:
A[1,0]=-1

In [24]:
A

array([[ 1,  1],
       [-1, -1]])

In [25]:
b=[1,-1]

In [26]:
b

[1, -1]

In [28]:
A=np.random.randint(-2**10,2**10,(10000,10000))

-inf

In [52]:
times=np.zeros(15)

In [53]:
for i in range(15):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [49]:
times

array([9.06000000e-05, 1.43000000e-04, 9.64999999e-05, 1.23900000e-04,
       7.41000000e-05, 1.07100000e-04, 9.96000000e-05, 2.56230000e-03,
       5.08950000e-03, 1.32647000e-02, 3.28440000e-02, 1.20990500e-01,
       6.70866900e-01, 2.93350250e+00, 2.26075319e+01])

In [54]:
times1=np.zeros(15)

In [55]:
times2=np.zeros(15)

In [56]:
for i in range(15):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times1[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=1)

In [57]:
for i in range(15):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times2[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [58]:
times3=np.zeros(16)

In [59]:
for i in range(16):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times3[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=1)

In [60]:
times4=np.zeros(16)

In [61]:
for i in range(16):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times4[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [62]:
times5=np.zeros(16)

In [63]:
for i in range(16):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times5[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [64]:
times6=np.zeros(17)

In [65]:
for i in range(17):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times6[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=1)

TypeError: __init__() missing 1 required positional argument: 'dtype'

In [ ]:
times7=np.zeros(17)

In [ ]:
for i in range(17):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times7[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [ ]:
times8=np.zeros(18)

In [ ]:
for i in range(18):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times8[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=1)

In [ ]:
times9=np.zeros(18)

In [ ]:
for i in range(18):
    n=2**i
    b=np.random.randint(-2**10,2**10,n)
    A=[[0]]
    while linalg.det(A)==0:
        A=np.random.randint(-2**10,2**10,(n,n))
    times9[i]=timeit.timeit("linalg.solve(A,b)",globals=globals(),number=10)

In [113]:
import time
def costam(n):
    print(1)

In [114]:
timeit.timeit("costam(10)",globals=globals(),number=12)

1
1
1
1
1
1
1
1
1
1
1
1


0.00038590000008298375

In [ ]:
tim=[] #time

In [ ]:
for i in [2,3,4,5,6,10,50,200,10000,20000,50000,10000]:
    tim.append("solve_n(i)",number=1)

In [30]:
random.randint(-50,50)

4

In [27]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [44]:
random.sample(range(0,2+1),4)

ValueError: Sample larger than population or is negative

In [71]:
np.random.randint(-20,20,(10,10))

array([[  0,  19,  16,   1,  -8,  12,   5,  -6,  10,  -7],
       [ 14,  -6,  11,  16,  14, -17,   1, -15,  -1,  10],
       [-20,   6, -19,  13,  10,  13,  -8,  -9, -18,  15],
       [ 14, -17,  17,  -8,  -3, -12,  -7,   7,   5,   5],
       [-18,  18,  19,   7, -12,  10,  10,   9, -17, -16],
       [-18,  12,  11,  -4,   6,  -9,  -4,  11, -15,  10],
       [  5,  14,  17, -15, -10,   4,   0,  10, -11,   9],
       [  1, -10, -13, -14,  -9,  11, -13,  -5,  -8,  -2],
       [  7,   8,  15, -19,   7, -20,  16,   2,  16,  10],
       [-17, -15,   2, -20,   5, -12,  14,   1,   4,  -4]])

# Zadanie 2

## Z poprzedniej listy
Implementacja stosu

In [2]:
import numpy as np

class Node:
    
    def __repr__(self):
        return str(self.data)
    
    def __init__(self,init_data):
        self.data = init_data
        self.next = None
  
    def get_data(self):
        return self.data

    def get_next(self):
        return self.next
  
    def set_data(self,new_data):
        self.data = new_data
  
    def set_next(self,new_next):
        self.next = new_next
    

class UnorderedList(object):
  
    def __init__(self):
        self.head = None

    def is_empty(self):
        return self.head == None

    def add(self, item):
        temp = Node(item)
        temp.set_next(self.head)
        self.head = temp

    def size(self):
        current = self.head
        count = 0
        while current != None:
            count = count + 1
            current = current.get_next()
        return count
    
    def search(self,item):
        current = self.head
        found = False
        while current != None and not found:
            if current.get_data() == item:
                found = True
            else:
                current = current.get_next()
        return found
    
    def remove(self, item):
        current = self.head
        previous = None
        found = False

        while not found:
            if current.get_data() == item:
                found = True
            else:
                previous = current
                current = current.get_next()

        if previous == None: #jeśli usuwamy pierwszy element
            self.head = current.get_next()
        else:
            previous.set_next(current.get_next())

##################################################################################################################   
#                                               Uzupełnienie                                                     #
##################################################################################################################   
            
    def append(self, item):
        """
        Metoda dodająca element na koniec listy.
        Przyjmuje jako argument obiekt, który ma zostać dodany.
        Niczego nie zwraca.
        """
        if self.head:
            current=self.head
            while current:
                previous=current
                current=current.get_next()
            previous.set_next(Node(item))
        else:
            self.add(item)
        
    
    def index(self, item):
        """
        Metoda podaje miejsce na liście, 
        na którym znajduje się określony element - 
        element pod self.head ma indeks 0.
        Przyjmuje jako argument element, 
        którego pozycja ma zostać określona.
        Zwraca pozycję elementu na liście lub None w przypadku, 
        gdy wskazanego elementu na liście nie ma.
        """
        current = self.head
        found = False
        i=0
        while current != None and not found:
            if current.get_data() == item:
                found = True
            else:
                current = current.get_next()
                i+=1
        return i if found else None
     
        
    def insert(self, pos, item):
        """
        Metoda umieszcza na wskazanej pozycji zadany element.
        Przyjmuje jako argumenty pozycję, 
        na której ma umiescić element oraz ten element.
        Niczego nie zwraca.
        Rzuca wyjątkiem IndexError w przypadku, 
        gdy nie jest możliwe umieszczenie elementu
        na zadanej pozycji (np. na 5. miejsce w 3-elementowej liście).
        """
        current = self.head
        previous=None
        while current != None and pos >0:
            pos-=1
            previous=current
            current=current.get_next()
            
        if pos == 0:
            if previous:
                if current:
                    previous.set_next(Node(item))
                    previous.get_next().set_next(current)
                else:
                    previous.set_next(Node(item))
            else:
                self.add(item)
        else:
            raise IndexError("Wyjście poza zakres")
                    
  
    def pop(self, pos=-1):
        """
        Metoda usuwa z listy element na zadaniej pozycji.
        Przyjmuje jako opcjonalny argument pozycję, 
        z której ma zostać usunięty element.
        Jeśli pozycja nie zostanie podana, 
        metoda usuwa (odłącza) ostatni element z listy. 
        Zwraca wartość usuniętego elementu.
        Rzuca wyjątkiem IndexError w przypadku,
        gdy usunięcie elementu z danej pozycji jest niemożliwe.
        """
        n=self.size()
        if pos + 1 > n or -pos > n:
            raise IndexError("Wyjście poza zekres")
        
        if pos > 0:
            i = pos
        elif pos == 0:
            temp=self.head
            self.head=self.head.get_next()
            return temp.get_data()
        else:
            i = n + pos
            
        current = self.head
        for _ in range(i-1):
            current = current.get_next()
        temp=current.get_next()
        current.set_next(current.get_next().get_next())
        return temp.get_data()
    
    
##################################################################################################################   
#                                               Dodatkowe                                                        #
##################################################################################################################   
            
    def __repr__(self):
        current=self.head
        tab=[]
        while current:
            tab.append(current.get_data())
            current=current.get_next()
        return str(tab)
    
    def reverse(self):
        """
        Metoda odwraca kolejność elementów w liście
        """
        temp=[]
        current=self.head
        while current:
            temp.append(current)
            current=current.get_next()
                    
        current=temp.pop()
        current.set_next(temp.pop())
        self.head=current
        
        
        while temp:
            current=current.get_next()
            current.set_next(temp.pop())
        current. get_next().set_next(None)
        
    def count(self, item):
        """
        Metoda zwraca liczbę danego elementu z listy
        """
        i=0
        current=self.head
        while current:
            i += 1 if current.get_data()==item else 0
            current = current.get_next()
        return i
            
    def shuffle(self):
        """
        Metoda permutuje listę
        """
        temp=[]
        current=self.head
        while current:
            temp.append(current)
            current=current.get_next()
            
        temp = [i for i in np.random.permutation(temp)]
                    
        current=temp.pop()
        current.set_next(temp.pop())
        self.head=current
        
        while temp:
            current=current.get_next()
            current.set_next(temp.pop())
        current.get_next().set_next(None)
        
    def __eq__(self, other):
        
        if type(other) == UnorderedList:
            current_self = self.head
            current_other = other.head
            
            while current_self and current_other:
                if current_self.get_data() != current_other.get_data():
                    return False
                current_self = current_self.get_next()
                current_other = current_other.get_next()
            if current_self or current_other:
                return False
            return True
        raise TypeError("'==' not supported between instances of 'UnorderedList' and '"+str(type(other).__name__)+"'")
            

    def same_element(self,other):
        """
        Sprawdza, czy kolejki mają takie same elementy (i ich liczbę)
        """
        temp_self = []
        temp_other = []
        current=self.head
        while current:
            temp_self.append(current.get_data())
            current = current.get_next()
            
        current=other.head
        while current:
            temp_other.append(current.get_data())
            current = current.get_next()
            
        while temp_self and temp_other:
            temp = temp_self.pop()
            for i in range(len(temp_other)):
                if temp==temp_other[i]:
                    temp_other.pop(i)
                    break
            else:
                return False
        return False if temp_self or temp_other else True
        
    def same_type_of_elements(self, other):
        """
        Sprawdza, czy wszystkie elementy jednego są w drugim
        """
        temp_self = []
        temp_other = []
        current=self.head
        while current:
            temp_self.append(current.get_data())
            current = current.get_next()
            
        current=other.head
        while current:
            temp_other.append(current.get_data())
            current = current.get_next()
            
        return all(i in temp_self for i in temp_other) and all(i in temp_other for i in temp_self)
    
    def __getitem__(self, pos):
        n=self.size()
        
        if pos + 1 > n or -pos > n:
            raise IndexError("Wyjście poza zekres")
            
        if pos > 0:
            i = pos
        elif pos == 0:
            return self.head.get_data()
        else:
            pos = n + pos
        
        current=self.head
        while current and pos > 0:
            current = current.get_next()
            pos-=1
        
        return current.get_data()
    
    def __contein__(self, item):
        return self.search(item)

    def __len__(self):
        return self.size()

In [8]:
class StackUsingUL(object):
    def __init__(self):
        self.items = UnorderedList()
    
    def is_empty(self):
        """
        Metoda sprawdzajacą, czy stos jest pusty.
        Nie pobiera argumentów.
        Zwraca True lub False.
        """
        return self.item.is_empty()
  
    def push(self, item):
        """
        Metoda umieszcza nowy element na stosie.
        Pobiera element, który ma zostać umieszczony.
        Niczego nie zwraca.
        """
        self.items.append(item)
    
    def pop(self):
        """
        Metoda ściąga element ze stosu.
        Nie przyjmuje żadnych argumentów.
        Zwraca ściągnięty element.
        Jeśli stos jest pusty, rzuca wyjątkiem IndexError.
        """

        return self.item.pop()

    def peek(self):
        """
        Metoda podaje wartość elementu na wierzchu stosu
        nie ściągajac go.
        Nie pobiera argumentów.
        Zwraca wierzchni element stosu.
        Jeśli stos jest pusty, rzuca wyjątkiem IndexError.
        """
        return self.item[-1]

    def size(self):
        """
        Metoda zwraca liczę elementów na stosie.
        Nie pobiera argumentów.
        Zwraca liczbę elementów na stosie.
        """
        return self.item.size()
    

In [4]:
def Hanoi(n:int, A:StackUsingUL, B:StackUsingUL, C:StackUsingUL):
    print(A)
    print(B)
    print(C)
    if n>0:
        hanoi(n-1,A,C,B)
        C.push(A.pop())
        hanoi(n-1,B,A,C)

In [10]:
A=StackUsingUL()
B=StackUsingUL()
C=StackUsingUL()

In [11]:
A.push(1)